Add BLS12-377 Precompiles
prestwich/go-ethereum pull request #1
Opened 2020-09-30 21:03 UTC by emaG3m

https://eips.ethereum.org/EIPS/eip-2537

2020-09-30 21:11 UTC, emaG3m commented on core/vm/contracts.go
> +func (c *bls12377G1Mul) Run(input []byte) ([]byte, error) {
Run interface is different in `go-ethereum`. 
`Run(input []byte, caller common.Address, evm *EVM, gas uint64) ([]byte, uint64, error)` ---> `Run(input []byte) ([]byte, error)`

2020-09-30 21:13 UTC, prestwich commented
should link to 2539 above :)

2020-09-30 21:23 UTC, prestwich commented on core/vm/contracts.go
> +func (c *bls12377G1Mul) Run(input []byte) ([]byte, error) {
it should be fine. I think celo-blockchain somewhat polluted the interface to add some of our weirder precompiles 😬

2020-09-30 21:26 UTC, prestwich commented on core/vm/contracts.go
> +	// Implements EIP-2537 G1Mul precompile.
should be 2539.
2537 is the old precompile. Please review throughout :)

2020-09-30 21:26 UTC, prestwich commented on core/vm/contracts.go
> +	// Implements EIP-2537 G1MultiExp precompile.
here too

2020-09-30 21:28 UTC, prestwich requested changes

2020-09-30 21:28 UTC, prestwich commented on params/protocol_params.go
> +
these can be populated from here:

https://github.com/ethereum/EIPs/pull/2999

2020-09-30 21:28 UTC, prestwich commented on params/protocol_params.go
> +var Bls12377MultiExpDiscountTable = [128]uint64{}
can be populated 

https://github.com/ethereum/EIPs/pull/2999

2020-10-01 16:29 UTC, prestwich approved these changes

2020-10-01 16:29 UTC, merged